name: alaman
description: A new Flutter project.
publish_to: 'none'

version: 1.7.2+46

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.3
  dio: ^4.0.0-beta7
  permission_handler: ^10.2.0
  flutter_svg: ^1.1.5
  dropdown_below: ^1.0.3
  dropdown_search: ^5.0.5
  toast: ^0.3.0
  http: ^0.13.1
  get: ^4.1.4
  auto_size_text: ^3.0.0
  get_storage: ^2.0.2
  flutter_rating_bar: ^4.0.0
  shared_preferences: ^2.0.5
  flutter_portal: ^1.1.3
  reactive_forms: ^14.1.0
  extended_nested_scroll_view: ^3.0.0
  font_awesome_flutter: ^10.3.0
  flutter_widget_from_html_core: ^0.9.0+2
  loading_skeleton: ^1.0.2
  flutter_cache_manager: ^3.0.2
  file_picker: ^5.0.1
  file_utils: ^1.0.0
  url_launcher: ^6.0.6
  flutter_screenutil: ^5.0.0+2
  http_auth: ^1.0.0
  flutter_switch: ^0.3.2
  slide_countdown: ^0.4.0
  smart_select: ^4.3.2
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.1
  cloud_firestore: ^4.2.0
  firebase_storage: ^11.0.8
  firebase_analytics: ^10.0.7
  firebase_messaging: ^14.2.1
  firebase_core_platform_interface: ^4.5.2

  rxdart: ^0.27.7
  edge_alert: ^0.0.1
  stripe_sdk:
    git: https://github.com/s2nventures/stripe-sdk
  package_info_plus: ^1.3.0
  percent_indicator: ^4.2.2
  loader_overlay: ^2.0.2+1
  flutter_spinkit: ^5.1.0
  razorpay_flutter: ^1.2.7
  open_document:
    git: https://github.com/emran92/open_document
  #advance_pdf_viewer: ^2.0.0  
  advance_pdf_viewer:
    git:
      url: https://github.com/lohanidamodar/pdf_viewer.git
      ref: 4e5d96be29de515f1081c0b6897741b8dca84722
  webview_flutter: ^3.0.0
  flutter_facebook_auth: ^5.0.7
  google_sign_in: ^5.2.4
  connection_notifier: ^1.0.1
  flutter_inappwebview:
    git:
      url: https://github.com/VictorUvarov/flutter_inappwebview
      ref: ios-16-compile-issue
  vdocipher_flutter: ^2.0.1
  flutter_paystack:
    git:
      url: https://github.com/definitelyme/flutter_paystack.git
      ref: a4a33c3dd0a12f46d655a2e63d11e9f20ba82d01
  eko_jitsi:
    git: https://github.com/emran92/eko_jitsi
  sn_progress_dialog: ^1.0.8
  fancy_shimmer_image: ^2.0.2
  purchases_flutter: ^4.2.1
  pod_player: ^0.1.0
  google_fonts: ^3.0.1
  transparent_image: ^2.0.0
  octo_image: ^1.0.2
  awesome_notifications: ^0.7.4+1
  another_flushbar: ^1.12.29
dependency_overrides:
  # freezed_annotation: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  import_sorter: ^4.6.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/appLogo.jpeg"

flutter_native_splash:
  background_image: "images/Splash.png"
  fullscreen: false

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: AvenirNext
      fonts:
        - asset: font/AvenirNextLTPro-Regular.otf